# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginandreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('travel', models.ManyToManyField(related_name='travelwith', to='loginandreg.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travler', to='loginandreg.User')),
            ],
        ),
    ]
